# Generated by Django 4.2 on 2026-02-11 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('lpg', models.IntegerField(default=0)),
                ('petrol', models.IntegerField(default=0)),
                ('diesel', models.IntegerField(default=0)),
                ('electricity', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Data',
                'verbose_name_plural': 'Daily Data',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
